[project]
name = "robot-training"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.*"
dependencies = [
    "cmake>=4.1.3",
    "ipykernel>=7.1.0",
    "lerobot[feetech,pi]",
    "numpy>=2.2.6",
    "opencv-python>=4.12.0.88",
    "pybind11>=3.0.1",
    "torch",
    "torchcodec",
    "torchvision"
]

[tool.uv.sources]
# Pin these packages to the index named "pytorch"
torch = { index = "pytorch" }
#torchcodec = { git = "https://github.com/pytorch/torchcodec.git", rev = "v0.9.1" }
lerobot = { path = "../lerobot", editable = true }
# Build Torchvision from Source (To match CUDA 13.0)
torchvision = { git = "https://github.com/pytorch/vision.git", branch = "main" }

[[tool.uv.index]]
# Define the index and give it a name
name = "pytorch"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.uv.extra-build-dependencies]
torchcodec = ["torch","numpy"]


