[project]
name = "robot-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipykernel>=7.1.0",
    "lerobot[all]>=0.4.3",
]

[tool.uv.sources]
lerobot = { path = "../lerobot", editable = true }
